//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Character
    {
        public string Name { get; set; }
        public string Race { get; set; }
        public string Power { get; set; }
        public string Prof { get; set; }
        public int ID { get; set; }
    }
}
